import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white py-4 shadow-md">
          <div className="container mx-auto px-4">
            <a href="/" className="text-2xl font-bold text-gray-800">IvyLink</a>
          </div>
        </nav>
        <div className="container mx-auto mt-8 px-4">{children}</div>
      </body>
    </html>
  );
}
